server:
  servlet:
    context-path: /

database:
  host: localhost
  port: 5432
  dbName: hamb

spring:
  application:
    name: hamb
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.dbName}
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

    #for create
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

      #for console show sql
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
